---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: vet
    pull: always
    image: golang:1.14.2
    commands:
      - go vet ./...
    volumes:
      - name: gopath
        path: /go

  - name: test
    pull: always
    image: golang:1.13.7
    commands:
      - go test -cover ./...
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}
---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: latest
    pull: always
    image: ymage/drone-kaniko:0.19.0
    settings:
      repo: ymage/drone-ansible
      dry_run: true
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        VERSION: ${DRONE_COMMIT_SHA:0:8}
    when:
      event:
        exclude:
          - tag

  - name: publish
    pull: always
    image: ymage/drone-kaniko:0.19.0
    settings:
      repo: ymage/drone-ansible
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_SEMVER_MAJOR}
        - ${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}
        - ${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}.${DRONE_SEMVER_PATCH}
        - ${DRONE_SEMVER}
        - ${DRONE_SEMVER_SHORT}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        VERSION: ${DRONE_TAG##v}
    when:
      event:
        - tag

depends_on:
  - testing

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: Rocket Notification
    image: rmilewski/drone-rocket:latest
    when:
      status:
        - success
        - failure
    settings:
      webhook:
        from_secret: rocket_chat_webhook
      channel: desordre
      username: desordre
      color:
        - value: green
          when:
            DRONE_BUILD_STATUS: success
        - value: red
          when:
            DRONE_BUILD_STATUS: failure
      message:
        - value: >
            [Build #${DRONE_BUILD_NUMBER}](${DRONE_BUILD_LINK}) succeeded.
            :thumbsup: Good job.
          when:
            DRONE_BUILD_STATUS: success
        - value: >
            [Build #${DRONE_BUILD_NUMBER}](${DRONE_BUILD_LINK}) failed.
            :disappointed: Fix ${DRONE_COMMIT_LINK} please.
      text: ${DRONE_COMMIT_MESSAGE}
      fields:
        - title: Author
          value: ${DRONE_COMMIT_AUTHOR} / ${DRONE_COMMIT_AUTHOR_EMAIL}
        - title: Git Repo
          value: "[${DRONE_REPO}](${DRONE_REMOTE_URL})"
        - title: Event
          value: ${DRONE_BUILD_EVENT}

depends_on:
  - linux-amd64
...
