---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: dryrun
    image: plugins/docker
    settings:
      auto_tag: true
      force_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ymage/drone-ansible
      tags: linux-amd64
      build_args:
        VERSION: ${DRONE_COMMIT_SHA:0:8}
      dry_run: true
    when:
      event:
        exclude:
          - tag

  - name: publish
    image: plugins/docker:linux-amd64
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ymage/drone-ansible
      build_args:
        VERSION: ${DRONE_TAG##v}
    when:
      event:
        - tag

trigger:
  ref:
    - refs/heads/master
    - "refs/tags/**"
    - "refs/pull/**"
...
